# Generated by Django 3.1.7 on 2021-03-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_botuser_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='activation_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
