# Generated by Django 3.1.7 on 2021-05-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.botuser'),
        ),
    ]
